clean: true
author: Reda Lemeden
author_url: https://redalemeden.com
copyright: "2018 © Reda Lemeden. See LICENSE for more details."
github_url: https://github.com/kaishin/gifu/
module: Gifu
module_version: 3.0.0
skip_undocumented: true
root_url: https://kaishin.github.io/
